#!/bin/bash
#Indra Bahadur Oli
playerList(){
  echo "Top 5 Worldcup played players"
  echo -e "Player Name \t\tPlayer Code"
  echo -e "Kagawa \t\t\tKAG"
  echo -e "Messi \t\t\tMES"
  echo -e "Rues \t\t\tREU"
  echo -e "LLoris \t\t\tLOR"
  echo -e "Coutinho \t\tCOU"

  setPlayer
}
choosePlayer(){
  PS3="Please choose any number form above list:- "
  select Players in $player1 $player2 $player3
  do
  	if [[ -z "$Players" ]]
  		then
  			echo "You typed a wrong figure. Please Try Again!"
  			choosePlayer #restart this function if input is wrong
  		else
  			echo "You choose '$Players' as your favourite player."
        if [[ $Players == KAG ]];
        then
          source Files
          kag
        elif [[ $Players == MES ]];
        then
          source Files
          mes
        elif [[ $Players == REU ]];
        then
          source Files
          reu
        elif [[ $Players == LOR ]];
        then
          source Files
          lor
        elif [[ $Players == COU ]];
        then
          source Files
          cou
        fi
        echo -e "Do you want restart the program (yes|no):- \c"
        read response
        if [[ $response == yes ]];
        then
          echo "Start from Country file"
          source Country
          WorldcupCountry
        fi
  	fi
  	break
  done
}
setPlayer(){
  echo -e "\nEnter any 3 Players code from above list (seperated by space):- \c"
  read player1 player2 player3
  if [ $player1 == "KAG" -o $player1 == "MES" -o $player1 == "REU" -o $player1 == "LOR" -o $player1 == "COU" ];
  then
    if [ $player2 == "KAG" -o $player2 == "MES" -o $player2 == "REU" -o $player2 == "LOR" -o $player2 == "COU" ];
    then
      if [ $player3 == "KAG" -o $player3 == "MES" -o $player3 == "REU" -o $player3 == "LOR" -o $player3 == "COU" ];
      then
        choosePlayer #run this function if user enter a 3 player code
      else
        echo -e "Third player name is not found in the database\nTry Again!"
        setPlayer
      fi
    else
      echo -e "Second player or more player is not found in the database\nTry Again!"
      setPlayer
    fi
  else
    echo -e "First player or more player is not found in the database\nTry Again!"
    setPlayer
  fi
}
